
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SANTIAGO
 */
public class frmHabitacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmHabitacion
     */
    public frmHabitacion() {
        initComponents();
        listarHabitacion();
        btnActualizar.setEnabled(false);
    }
    public void listarHabitacion(){
        DefaultTableModel modeloHabitacion = new DefaultTableModel();
        modeloHabitacion.addColumn("N. Habitacion");
        modeloHabitacion.addColumn("Tipo");
        modeloHabitacion.addColumn("Estado");
        modeloHabitacion.addColumn("Precio x Noche");
        tablaHabitacion.setModel(modeloHabitacion);
        try{
            Coneccion cn = new Coneccion();
            Connection cnx = cn.conectar();
            modeloHabitacion = (DefaultTableModel) tablaHabitacion.getModel();
            Statement ps;
            ResultSet rs;
            ps=cnx.createStatement();
            rs=ps.executeQuery("SELECT * FROM habitaciones");
            while(rs.next()){
                String fila [] = new String [4];
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);

                modeloHabitacion.addRow(fila);
                tablaHabitacion.setModel(modeloHabitacion);
            }
            
        } catch(Exception ex){
             Logger.getLogger(frmHabitacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNumero.requestFocus();
    }
    public void limpiarHabitacion(){
        txtNumero.setText("");
        cbxTipo.setSelectedIndex(0);
        cbxEstado.setSelectedIndex(0);
        txtPrecio.setText("");
        txtNumero.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        cbxTipo = new javax.swing.JComboBox<>();
        cbxEstado = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHabitacion = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Habitaciones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtNumero.setBorder(javax.swing.BorderFactory.createTitledBorder("N. Habitacion"));

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..", "Simple", "Doble", "Suit" }));

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Disponible", "Mantenimiento" }));

        txtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio X Noche"));

        jLabel3.setText("Tipo:");

        jLabel4.setText("Estado:");

        tablaHabitacion.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tablaHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaHabitacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaHabitacion);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_Search32.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_Save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_Sync.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_Delete32.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_Cancel32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrecio)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscar))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!txtNumero.getText().equals("") && !cbxTipo.getSelectedItem().equals("...") && !cbxEstado.getSelectedItem().equals("...") && !txtPrecio.getText().equals("") ) {
            Coneccion cn = new Coneccion();
            Connection cnx = cn.conectar();

            try 
            {
                PreparedStatement pst = cnx.prepareStatement("INSERT INTO habitaciones(Numero, Tipo, Estado, Precio) VALUES (?,?,?,?);");
                pst.setString(1, txtNumero.getText());
                pst.setString(2, cbxTipo.getSelectedItem().toString());
                pst.setString(3, cbxEstado.getSelectedItem().toString());
                pst.setDouble(4, Double.parseDouble(txtPrecio.getText()));
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "HABITACIÓN REGISTRADA");
                limpiarHabitacion();
            } catch (SQLException ex) {
                Logger.getLogger(frmHabitacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else{
            JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS CAMPOS");
        }
  
        listarHabitacion();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (!txtNumero.getText().equals("")) {
            Coneccion cn = new Coneccion();
            Connection cnx = cn.conectar();

            try 
            {
                PreparedStatement pst = cnx.prepareStatement("SELECT * FROM habitaciones WHERE Numero = ?");
                pst.setString(1, txtNumero.getText());
                ResultSet rs =pst.executeQuery();
                if (rs.next()) {
                    cbxTipo.setSelectedItem(rs.getString("Tipo"));
                    cbxEstado.setSelectedItem(rs.getString("Estado"));
                    txtPrecio.setText(rs.getString("Precio"));
                    btnActualizar.setEnabled(true);
                    btnGuardar.setEnabled(false);
                    
                } else{
                    JOptionPane.showMessageDialog(null, "ESTA HABITACIÓN NO ESTA REGISTRADA");
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmHabitacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else{
            JOptionPane.showMessageDialog(null, "DEBE INGRESAR EL NUMERO");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaHabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaHabitacionMouseClicked
        // TODO add your handling code here:
        int fila = tablaHabitacion.getSelectedRow();
        txtNumero.setText((String)tablaHabitacion.getValueAt(fila, 0));
        cbxTipo.setSelectedItem((String)tablaHabitacion.getValueAt(fila, 1));
        cbxEstado.setSelectedItem((String)tablaHabitacion.getValueAt(fila, 2));
        txtPrecio.setText((String)tablaHabitacion.getValueAt(fila, 3));
        
        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(true);
    }//GEN-LAST:event_tablaHabitacionMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        if (!txtNumero.getText().equals("") && !cbxTipo.getSelectedItem().equals("...") && !cbxEstado.getSelectedItem().equals("...") && !txtPrecio.getText().equals("") ) {
            Coneccion cn = new Coneccion();
            Connection cnx = cn.conectar();

            try 
            {
                PreparedStatement pst = cnx.prepareStatement("UPDATE habitaciones SET Tipo = ?, Estado = ?, Precio = ? WHERE Numero = ?");
                pst.setString(1, cbxTipo.getSelectedItem().toString());
                pst.setString(2, cbxEstado.getSelectedItem().toString());
                pst.setDouble(3, Double.parseDouble(txtPrecio.getText()));
                pst.setString(4, txtNumero.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "HABITACIÓN ACTUALIZADA");
                limpiarHabitacion();
                btnActualizar.setEnabled(false);
                btnGuardar.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(frmHabitacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else{
            JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS CAMPOS");
        }
        listarHabitacion();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (!txtNumero.getText().equals("")) {
            Coneccion cn = new Coneccion();
            Connection cnx = cn.conectar();

            try {
                PreparedStatement pst = cnx.prepareStatement("DELETE FROM habitaciones WHERE Numero = ?");
                pst.setString(1, txtNumero.getText());
                pst.executeUpdate();
                limpiarHabitacion();
                JOptionPane.showMessageDialog(null, "HABITACIÓN ACTUALIZADA");
                btnActualizar.setEnabled(false);
                btnGuardar.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(frmHabitacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else{
            JOptionPane.showMessageDialog(null, "DEBE INGRESAR UN NUMERO");
        } 
           listarHabitacion();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarHabitacion();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHabitacion;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
